### PR TITLE
hotfix(wildpath): set user empty value

### PR DESCRIPTION
**Pull request by 1046102779**
router: /v1.0/publish/{topic:*}
request uri: /v1.0/publish/

the topic field's value is empty string. why is "/" string ?

### CODE REVIEW

**Comment by 1046102779** [comment]
comment: https://github.com/dapr/dapr/blob/master/pkg/http/api.go#L1154

**Comment by 1046102779** [comment]
@savsgio please review pr

**Comment by savsgio** [comment]
Hi @1046102779,

Could you make a test to fulfill the 100% of coverage, please?

**Comment by savsgio** [comment]
And add the same condition here: https://github.com/fasthttp/router/blob/master/radix/node.go#L391

**Comment by savsgio** [comment]
Fix here too, please: https://github.com/fasthttp/router/blob/master/radix/tree.go#L89 , and will merge it.

```go
ctx.SetUserValue(t.root.wildcard.paramKey, "")
```

Thanks

**Comment by savsgio** [comment]
@1046102779  ??

**Comment by 1046102779** [comment]
> @1046102779 ??

i create anew pr

**Pull request closed without merging**
