### PR TITLE
Added fasthttprouter-prometheus package

### PR DESCRIPTION
**Pull request by Mnwa**
More about pr [on thats issue](https://github.com/fasthttp/router/issues/14)

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@Mnwa Hi!

I see several issues here.

1) you really need to enable issues in the repo
2) in the original repository, there's no license applied. by default, it means that this source code is copyrighted material and protected by copyright law of the original author's country of residence. this means, that you need an explicit written permission to use, modify, and redistribute the copyrighted source code under another license. or, of course, the original author may also apply a license to his work. therefore, that license should permit the same actions as described above, except the right to change the license
3) GPL, AGPL etc. are dangerous for use in commercial products due to the fact that license requires you to disclose source code publicly without requiring a special password or key for unpacking, reading or copying, and in case of a trial the court may decide that the company must disclose proprietary source code of its products. I'd strongly recommend you to switch over to Apache 2.0 due to the fact that this license does not require you to disclose source code including the case of commercial usage.

**Comment by Mnwa** [comment]
@kirillDanshin Hey! Thank you for review! I enabled issues and dropped license for now. Also I created [issue](https://github.com/flf2ko/fasthttp-prometheus/issues/4) where asked for add a license to the repo.

**Comment by Mnwa** [comment]
@kirillDanshin author flf2ko/fasthttp-prometheus added MIT license to repository and I'm cherry picked it to Mnwa/fasthttprouter-prometheus

**Comment by kirillDanshin** [comment]
@Mnwa https://github.com/flf2ko/fasthttp-prometheus/issues/4#issuecomment-533791891

**Comment by OrlovEvgeny** [comment]
what for?
[github.com/valyala/fasthttp/fasthttpadaptor](https://github.com/valyala/fasthttp/tree/master/fasthttpadaptor) already exists for this

it is much easier

```
r := router.New()
wrap := fasthttpadaptor.NewFastHTTPHandler(promhttp.Handler())
r.GET("/metrics", wrap)
```

why do we need an extra overhead if fasthttp already supports it?

**Pull request closed without merging**
