### PR TITLE
📦 NEW: Router Grouping

### PR DESCRIPTION
**Pull request by AnikHasibul**
^_^

### CODE REVIEW

**Comment by AnikHasibul** [comment]
Grouping example:

```
r := router.New()
api := r.Group("/api")
api.GET("/bar",bar)
v1 := api.Group("/v1")
v1.GET("/foo", foo)
```

**Comment by kirillDanshin** [comment]
Nice feature, thanks :)

Another option is to use gramework's API:

```
v1 := r.Sub("/v1") // version subrouter
examplev1.Register(v1) // func Register(*SubRouter)
```
*SubRouter can be used to accept only subrouters. this usually helps when you have multiple version-based packages

**Comment by AnikHasibul** [comment]
I think this pull request will get merged, and I am also requesting a versioned release after merging this, for working with gomodule.

**Comment by savsgio** [comment]
Sorry for my delay. I will merge it.

Tomorrow I will release a new version.

**Pull request merged**
